ci: install python dependencies

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,5 +17,30 @@ jobs:
       - uses: actions/setup-node@v2
         with:
           node-version: 20
+
+      - name: Setup Python and Install distutils (if needed)
+        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.x'
+      - name: Install Python and set path on Ubuntu
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y python3 python3-distutils python3-setuptools
+          python3 -m distutils --version || echo "distutils not found"
+          npm config set python $(which python3)
+          echo "Python path set to $(which python3)"
+      - name: Install Python dependencies for node-gyp on macOS
+        if: ${{ matrix.os == 'macos-latest' }}
+        run: |
+          brew install python@3.9
+          echo "Setting Python version for node-gyp"
+          npm config set python $(which python3)
+      - name: Install Python dependencies for node-gyp on Windows
+        if: ${{ matrix.os == 'windows-latest' }}
+        run: |
+          npm config set python $(where python)
+
       - run: npm install
       - run: npm test
